Update feautre_nodeJs.yml

diff --git a/.github/workflows/feautre_nodeJs.yml b/.github/workflows/feautre_nodeJs.yml
--- a/.github/workflows/feautre_nodeJs.yml
+++ b/.github/workflows/feautre_nodeJs.yml
@@ -66,7 +66,25 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_GITHUBACTION }}
           SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
-
+      - name: Quality check for SonarCloud
+        env:
+          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+               curl -s
+               https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{secrets.SONAR_PROJECT_KEY }} -o result.json
+               cat result.json
+               if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
+                  echo "Quality gate failed."
+                  exit 1
+               else
+                  echo "Quality gate passed."
+               fi
+               failedConditions=$(jq -r '.projectStatus.conditions[] | select(.status == "ERROR") | "\(.metricKey): \(.actualValue) (threshold: \(.errorThreshold))"' result.json)
+               if [ -n "$failedConditions" ]; then
+                 echo "Failed Conditions:"
+                 echo "$failedConditions"
+               fi
    notify-success:
     name: Send Slack Notification - Success
     runs-on: ubuntu-latest
